name: boxch_server
version: 1.0.0+2

description: 

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  http: ^0.13.3
  test: ^1.17.11
  solana: ^0.22.0
  hex: ^0.2.0

dev_dependencies:
